use database DEMO;
USE SCHEMA PUBLIC;

------Load table and create Primary Key

CREATE OR REPLACE TABLE KI_SALES_DATA
(order_id VARCHAR(20) PRIMARY KEY,
 order_date	string,
 ship_date string,
 ship_mode CHAR(15),
 customer_name VARCHAR(25),
 segment CHAR(12),
 state VARCHAR(150),
 country VARCHAR(35),
 market CHAR(7),
 region CHAR(15),
 product_id	CHAR(20),
 category CHAR(16),
 sub_category CHAR(15),
 product_name STRING,
 sales number(6,0),
 quantity INT,
 discount float,
 profit float,
 shipping_cost float,
 order_priority CHAR(8),
 year CHAR(4)
 );

DESCRIBE TABLE KI_SALES_DATA;

-------CREATE A COPY OF TABLE

CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT*FROM KI_SALES_DATA;


SELECT*FROM KI_SALES_DATA_COPY;

--------2. CHECK THE ORDER DATE AND SHIP DATE TYPE AND THINK IN WHICH DATA TYPE YOU HAVE TO 
CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT*,
TO_CHAR(DATE(ORDER_DATE,'MM-DD-YYYY'),'YYYY-MM-DD') AS ORDER_DATE2
FROM KI_SALES_DATA_COPY;

CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT*,
TO_CHAR(DATE(SHIP_DATE,'MM-DD-YYYY'),'YYYY-MM-DD') AS SHIP_DATE2
FROM KI_SALES_DATA_COPY;


-------3. EXTACT THE LAST NUMBER AFTER THE - AND CREATE OTHER COLUMN AND UPDATE IT.

CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT*, REGEXP_SUBSTR(ORDER_ID,'[[:digit:]]+',1,2) AS ORDER_NUMBER
from KI_SALES_DATA_COPY;

-------4.FLAG ,IF DISCOUNT IS GREATER THEN 0 THEN  YES ELSE FALSE AND PUT IT IN NEW COLUMN FRO EVERY ORDER ID
CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT *,
      CASE
        WHEN DISCOUNT>0 THEN 'Yes'
        ELSE 'False'
      END AS VALID_DISCOUNT
FROM KI_SALES_DATA_COPY;
      
--------5. FIND OUT THE FINAL PROFIT AND PUT IT IN COLUMN FOR EVERY ORDER ID.

SELECT
SUM(PROFIT) FROM KI_SALES_DATA_COPY AS OVERALL_PROFT;

-------6. FIND OUT HOW MUCH DAYS TAKEN FOR EACH ORDER TO PROCESS FOR THE SHIPMENT FOR EVERY ORDER ID

CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT*,
DATEDIFF('days',ORDER_DATE2,SHIP_DATE2) as DAYS_TAKEN_TO_PROCESS_TO_SHIP
FROM KI_SALES_DATA_COPY;

-------7. FLAG THE PROCESS DAY AS BY RATING IF IT TAKES LESS OR EQUAL 3  DAYS MAKE 5,LESS OR EQUAL THAN 6 DAYS BUT MORE THAN 3 MAKE 4,LESS THAN 10 BUT MORE THAN 6 MAKE 3,MORE THAN 10 MAKE IT 2 FOR EVERY ORDER ID

CREATE OR REPLACE TABLE KI_SALES_DATA_COPY AS
SELECT*, 
    CASE
       WHEN DAYS_TAKEN_TO_PROCESS_TO_SHIP <=3 THEN 5
       WHEN DAYS_TAKEN_TO_PROCESS_TO_SHIP BETWEEN 4 AND 6 THEN 4
       WHEN DAYS_TAKEN_TO_PROCESS_TO_SHIP BETWEEN 7 AND 10 THEN 3
       ELSE 2
     END AS RATING
FROM KI_SALES_DATA_COPY;
  

